apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-demo
  namespace: github-demo
spec:
  replicas: 2

  selector:
    matchLabels:
      app: github-demo

  template:
    metadata:
      labels:
        app: github-demo

    spec:
      containers:
        - name: github-demo
          image: ghcr.io/petkancho987/testk8s:d4de088

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "250m"
              memory: "256Mi"
